# Generated by Django 4.0.4 on 2022-05-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'My TODO LIST'},
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
